name: drugsignet
channels:
  - conda-forge
dependencies:
  - r-base=4.5
  - r-pak
  - r-reticulate
  - r-knitr
  - r-rmarkdown
  - pandoc
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - make
  - cmake
  - pkg-config
  - openjdk
  - zlib
  - bzip2
  - xz
  - libcurl
  - openssl
  - libxml2
  - icu
  - sqlite
  - gsl
  - glpk
  - libpng
  - libjpeg-turbo
  - libtiff
  - cairo
  - fontconfig
  - freetype
  - harfbuzz
  - fribidi
  - xorg-libx11
  - xorg-libxt
  - libssh2
  - libgit2
  - udunits2
  - gmp
  - mpfr
  - python=3.10
  - graph-tool
  - numpy
  - pandas
  - scipy
  - networkx
  - joblib
  - tqdm
  - openpyxl
  - jinja2
  - markupsafe
  - pip
  - pip:
      - kaleido
      - synapseclient==4.4.2
